pipelines:
  - name: validate
    steps:
      - name: ls
        type: bash
        configuration:
          timeoutSeconds: 120
          affinityGroup: ag1
          priority: 1
          nodePool: pool1
        setup:
          environmentVariables:
            normal:
              foo: bar
              fizz: bin
          runtime:
            type: image
            image:
              auto:
                language: foo
                versions:
                  - 1.2.3
        execution:
          onExecute:
            - foo
