pipelines:
  - name: validate
    steps:
      - name: ls
        type: bash
        configuration:
          timeoutSeconds: 120
          affinityGroup: ag1
          priority: 1
          nodePool:
            - pool1
            - pool2
        xecution:
          onExecute:
            - foo
