resources:
  - name: dockerbuild_gitRepo
    type: gitRepo
    repoPath: skylark05/dockerbuild
    configuration:
      integrationName: github
    version:
      sha: master
      
  - name: my_files
    type: file
    configuration:
      integrationName: art
    version:
      pattern: ragesh-generic/test-foo*.txt
      
pipelines:
  - name: app
    steps:
      - name: build_image
        type: build
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: mill.jfrog.info:12052/docker/ragesh
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - art
            - my_files
          resources:
            - dockerbuild_gitRepo
