resources:
  - name: dockerbuild_gitRepo
    type: gitRepo
    repoPath: skylark05/dockerbuild
    configuration:
      integrationName: github
    version:
      sha: master
      
  - name: my_files
    type: file
    configuration:
      integrationName: art
    version:
      pattern: ragesh-generic/test-foo*.txt
        
  - name: my_in_buildInfo
    type: buildInfo
    version:
      buildNumber: 35
      buildName: file_push_to_art_with_in_and_out_resource
      
  - name: my_out_buildInfo
    type: buildInfo
    version:
      buildNumber: 35
      buildName: file_push_to_art_with_in_and_out_resource
    
pipelines:
  - name: promote
    steps:
      - name: promote
        type: promote
        setup:
          promote:
            targetRepo: ragesh-promoted
        requires:
          integrations:
            - art
          resources:
            - my_in_buildInfo
        outputResources:
          - my_out_buildInfo
  - name: app
    steps:
      - name: build_image
        type: build
        payloadType: docker
        execution:
          onStart:
            - cat $STEP_TMP_DIR/fileSpecs.json
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: mill.jfrog.info:12052/docker/ragesh
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - art
          resources:
            - dockerbuild_gitRepo
            - my_files
            
      - name: push_image
        type: push
        setup:
          push:
            targetRepo: docker
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - build_image
            
      - name: publish_build
        type: publish
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - push_image
            
      - name: promote_build
        type: promote
        setup:
          promote:
            targetRepo: ragesh-promoted
            includeDependencies: true
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - publish_build
