resources:
  - name: busybox_img
    type: image
    imageName: busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
    
pipelines:
  - name: pipe1
    steps:
      - name: docker_push_to_art
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: docker
               targetRepo: docker
               inputImageName: busybox
               inputImageTag: latest
               #outputImageName: mill.jfrog.info:12052/$targetRepo/busybox
               outputImageName: ragesh/busybox
               outputImageTag: step.$STEP_ID
        requires:
          resources:
            - busybox_img
          integrations:
            - docker
