resources:
  - name: in_file_rt
    type: file
    
  - name: busybox_rt_img
    type: image
    imageName: mill.jfrog.info:12052/docker/busybox
    configuration:
      integrationName: art
    initialVersion:
      imageTag: latest
  - name: busybox_rt_out_img
    type: image
    imageName: mill.jfrog.info:12052/docker/ragesh
    configuration:
      integrationName: art
    initialVersion:
      imageTag: latest
  - name: busybox_img
    type: image
    imageName: busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
  - name: busybox_out_img
    type: image
    imageName: ragesh/busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
      
pipelines:
  - name: push_file
    steps:
      - name: file_push_to_art_without_resources
        type: push
        payloadType: file
        setup:
          environmentVariables:
            normal:
              outputIntegrationName: art
              outputFileLocation: ragesh-generic
              outputFileName: nvm.sh
              inputFileLocation: .
              inputFileName: nvm.sh
        requires:
          integrations:
            - art
        execution:
          onStart:
            - wget https://raw.githubusercontent.com/nvm-sh/nvm/master/nvm.sh -O ./nvm.sh
      - name: file_push_to_art_with_in_resource
        type: push
        payloadType: file
        setup:
          environmentVariables:
            normal:
              outputIntegrationName: art
              outputFileLocation: ragesh-generic
              outputFileName: nvm.sh
        requires:
          resources:
            - in_file_rt
          integrations:
            - art
  - name: pipe1
    steps:
      - name: docker_push_to_dh_with_in_out_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputImageTag: step.$STEP_ID
        requires:
          resources:
            - busybox_img
          integrations:
            - docker
        outputResources:
          - busybox_out_img
      - name: docker_push_to_dh_with_no_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: docker
               inputImageName: busybox
               inputImageTag: latest
               outputImageName: ragesh/busybox
               outputImageTag: step.$STEP_ID
        requires:
          integrations:
            - docker
      - name: docker_push_to_dh_with_in_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: docker
               outputImageName: ragesh/busybox
               outputImageTag: step.$STEP_ID
        requires:
          resources:
            - busybox_img
          integrations:
            - docker
      - name: docker_push_to_dh_with_out_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               inputImageName: busybox
               inputImageTag: latest
               outputImageTag: step.$STEP_ID
        requires:
          integrations:
            - docker
        outputResources:
          - busybox_out_img
      - name: docker_push_to_rt_with_no_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: art
               inputImageName: mill.jfrog.info:12052/docker/busybox
               inputImageTag: latest
               outputImageName: mill.jfrog.info:12052/docker/ragesh
               outputImageTag: step.$STEP_ID
               targetRepo: docker
        requires:
          integrations:
            - art
      - name: docker_push_to_rt_with_in_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: art
               outputImageName: mill.jfrog.info:12052/docker/ragesh
               outputImageTag: step.$STEP_ID
               targetRepo: docker
        requires:
          resources:
            - busybox_rt_img
          integrations:
            - art
      - name: docker_push_to_art_with_out_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               inputImageName: mill.jfrog.info:12052/docker/busybox
               inputImageTag: latest
               outputImageTag: step.$STEP_ID
               targetRepo: docker
        requires:
          integrations:
            - docker
        outputResources:
          - busybox_rt_out_img
          
      - name: docker_push_to_art_with_in_out_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputImageTag: step.$STEP_ID
               targetRepo: docker
        requires:
          resources:
            - busybox_rt_img
          integrations:
            - docker
        outputResources:
          - busybox_rt_out_img
