pipelines:
  - name: pipe1
    steps:
      - name: build_img
        type: bash
        execution:
          onExecute:
            - docker pull busybox:latest
            - docker tag busybox:latest 35.238.107.196/busybox:ragesh
      - name: push_to_art
        type: pushToArtifactory
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               targetRepo: docker-local
               imageTag: 35.238.107.196/busybox:ragesh
        triggeredBy:
          steps:
            - build_img
        requires:
          integrations:
            - art
