resources:
  - name: busybox_img
    type: image
    imageName: busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
  - name: busybox_out_img
    type: image
    imageName: ragesh/busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
      
pipelines:
  - name: pipe1
    steps:
      - name: docker_push_to_dh_with_in_out_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputImageTag: step.$STEP_ID
        requires:
          resources:
            - busybox_img
          integrations:
            - docker
        outputResources:
          - busybox_out_img
      - name: docker_push_to_dh_with_no_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: docker
               inputImageName: busybox
               inputImageTag: latest
               outputImageName: ragesh/busybox
               outputImageTag: step.$STEP_ID
        requires:
          integrations:
            - docker
      - name: docker_push_to_dh_with_in_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               outputIntegrationName: docker
               outputImageName: ragesh/busybox
               outputImageTag: step.$STEP_ID
        requires:
          resources:
            - busybox_img
          integrations:
            - docker
      - name: docker_push_to_dh_with_out_resources
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               inputImageName: busybox
               inputImageTag: latest
               outputImageTag: step.$STEP_ID
        requires:
          integrations:
            - docker
        outputResources:
          - busybox_out_img
