resources:
  - name: busybox_img
    type: image
    imageName: busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
  - name: busybox_out_img
    type: image
    imageName: ragesh/busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest
      
pipelines:
  - name: pipe1
    steps:
      - name: docker_push_to_art
        type: push
        payloadType: docker
        setup:
          environmentVariables:
            normal:
               targetRepo: docker
               outputImageTag: step.$STEP_ID
        requires:
          resources:
            - busybox_img
          integrations:
            - docker
        outputResources:
          - busybox_out_img
