resources:
  - name: img_1
    type: image
    imageName: ragesh/busybox
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest

pipelines:
  - name: pipe1
    steps:
      - name: push_to_art
        type: pushToArtifactory
        payloadType: file
        setup:
          environmentVariables:
            normal:
               targetPath: value1
               sourcePath: value2
        requires:
          integration:
            - art
            
      - name: start
        type: bash
        requires:
          resources:
            - img_1
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: top1
        type: bash
        triggeredBy:
          steps:
            - start
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: top2
        type: bash
        triggeredBy:
          steps:
            - top1
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: top3
        type: bash
        requires:
          resources:
            - img_1
        triggeredBy:
          steps:
            - top2
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: bottom1
        type: bash
        triggeredBy:
          steps:
            - start
        execution:
          onExecute:
            - echo "Hello, world!"
      - name: final
        type: bash
        triggeredBy:
          steps:
            - top3
            - bottom1
        execution:
          onExecute:
            - echo "Hello, world!"
